/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#191c1d',
        'on-surface-variant': '#5b403f',
        'on-primary-fixed': '#410007',
        'on-secondary-fixed': '#1b1b1c',
        primary: '#b7122a',
        'on-primary': '#ffffff',
        'primary-container': '#db313f',
        'surface-container-high': '#ffe1e0',
        'surface-container-low': '#fff0ef',
        'tertiary-fixed-dim': '#c5c7c8',
        background: '#fff8f7',
        'surface-container': '#ffe9e8',
        'surface-dim': '#f0d3d2',
        'on-background': '#271717',
        'secondary-container': '#e2dfe0',
        'surface-bright': '#fff8f7',
        'on-tertiary-fixed-variant': '#454748',
        'surface-variant': '#f9dcda',
        'on-primary-fixed-variant': '#92001c',
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
        'secondary-fixed': '#e5e2e3',
        'primary-fixed': '#ffdad8',
        'primary-fixed-dim': '#ffb3b1',
        tertiary: '#5a5c5d',
        'on-primary-container': '#fffbff',
        'inverse-surface': '#3e2c2b',
        'surface-tint': '#bb162c',
        surface: '#fff8f7',
        outline: '#8f6f6e',
        'surface-container-highest': '#f9dcda',
        secondary: '#5f5e5f',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#737576',
        'on-tertiary-container': '#fcfdfe',
        'on-secondary-fixed-variant': '#474647',
        'outline-variant': '#e4bebc',
        'tertiary-fixed': '#e1e3e4',
        error: '#ba1a1a',
        'on-secondary-container': '#636263',
        'on-surface': '#271717',
        'secondary-fixed-dim': '#c8c6c7',
        'inverse-primary': '#ffb3b1',
        'on-tertiary': '#ffffff',
        'inverse-on-surface': '#ffedeb',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        md: '16px',
        sm: '8px',
        gutter: '16px',
        xs: '4px',
        base: '4px',
        xl: '40px',
        'container-max': '1280px',
        'margin-desktop': '32px',
        lg: '24px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'display-lg': ['Inter'],
        'label-sm': ['Inter'],
        'headline-md': ['Inter'],
        'headline-md-mobile': ['Inter'],
        'label-bold': ['Inter'],
        'display-lg-mobile': ['Inter'],
        'body-lg': ['Inter'],
        'headline-sm': ['Inter'],
        'body-md': ['Inter'],
      },
      fontSize: {
        'display-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-md': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'headline-md-mobile': ['22px', { lineHeight: '28px', fontWeight: '600' }],
        'label-bold': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' },
        ],
        'display-lg-mobile': ['28px', { lineHeight: '34px', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        typing: {
          '0%, 80%, 100%': { transform: 'scale(0)' },
          '40%': { transform: 'scale(1)' },
        },
      },
      animation: {
        shimmer: 'shimmer 3s infinite linear',
        typing: 'typing 1.4s infinite ease-in-out both',
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
};

